[[main]]
  name = "Docs"
  url = "/docs/basics/copy-the-template/"
  identifier = "docs"
  weight = 1

    [[main]]
      name = "Basics"
      weight = 10
      identifier = "docs-basics"
      url = "/docs/basics/start-here"
      parent = "docs"

    [[main]]
      name = "Features"
      weight = 20
      identifier = "docs-features"
      url = "/docs/features/code-tabs/"
      parent = "docs"

    [[main]]
      name = "Menus"
      weight = 30
      identifier = "docs-menus"
      url = "/docs/menus/dropdown/"
      parent = "docs"


[[main]]
  name = "Reference"
  url = "/docs/basics/copy-the-template/"
  weight = 1
  identifier = "reference"

    [[main]]
      name = "Commands"
      weight = 10
      identifier = "reference-commands"
      url = "/reference/commands"
      parent = "reference"

    [[main]]
      name = "Configuration"
      weight = 20
      identifier = "reference-configuration"
      url = "/reference/configuration"
      parent = "reference"

    [[main]]
      name = "Front-matter"
      weight = 30
      identifier = "reference-front-matter"
      url = "/reference/front-matter"
      parent = "reference"

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 20



[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/protocol/docs-starter"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/protocollabs"
  weight = 20



[[footer]]
  name = "Privacy"
  url = "/privacy"
  weight = 10

[[footer]]
  name = "Terms"
  url = "/terms"
  weight = 20

[[footer]]
  name = "Contact"
  url = "/contact"
  weight = 30
